name: binder_test
channels:
    - conda-forge
dependencies:
    - python=3.8
    - cmake
    - gfortran
    - matplotlib 
    - numpy=1.19.5
    - jinja2 
    - pyzmq
    - gym=0.19.0
    - stable-baselines3=1.4.0
      
